// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Navigation → Menu Items*
 */
export interface NavigationDocumentDataMenuItemsItem {
  /**
   * Label field in *Navigation → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The label for the menu item.
   * - **API ID Path**: navigation.menu_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Menu Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: The link the menu item should lead to.
   * - **API ID Path**: navigation.menu_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Website Name field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The name of the website.
   * - **API ID Path**: navigation.website_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_name: prismic.KeyTextField;

  /**
   * Menu Items field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_items: prismic.GroupField<Simplify<NavigationDocumentDataMenuItemsItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice = NavigationSlice | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The title of the page.
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ReviewDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Review documents
 */
interface ReviewDocumentData {
  /**
   * Product Name field in *Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The name of the product being reviewed.
   * - **API ID Path**: review.product_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_name: prismic.KeyTextField;

  /**
   * Review Date field in *Review*
   *
   * - **Field Type**: Date
   * - **Placeholder**: The date this review was created.
   * - **API ID Path**: review.review_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  review_date: prismic.DateField;

  /**
   * Spiciness field in *Review*
   *
   * - **Field Type**: Select
   * - **Placeholder**: The spiciness level of the product (1 = mild, 5 = hot).
   * - **API ID Path**: review.spiciness
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  spiciness: prismic.SelectField<"1" | "2" | "3" | "4" | "5">;

  /**
   * Rating field in *Review*
   *
   * - **Field Type**: Select
   * - **Placeholder**: The rating of the product (1 = poor, 5 = excellent).
   * - **API ID Path**: review.rating
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  rating: prismic.SelectField<"1" | "2" | "3" | "4" | "5">;

  /**
   * Review Text field in *Review*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: The text containing the review.
   * - **API ID Path**: review.review_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  review_text: prismic.RichTextField;

  /**
   * Product Image field in *Review*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: review.product_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Review*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: review.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ReviewDocumentDataSlicesSlice> /**
   * Meta Title field in *Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: review.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: review.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Review*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: review.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Review document from Prismic
 *
 * - **API ID**: `review`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ReviewDocumentData>, "review", Lang>;

export type AllDocumentTypes =
  | NavigationDocument
  | PageDocument
  | ReviewDocument;

/**
 * Item in *Navigation → Default → Primary → Menu Items*
 */
export interface NavigationSliceDefaultPrimaryMenuItemsItem {
  /**
   * Label field in *Navigation → Default → Primary → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.menu_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Default → Primary → Menu Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.menu_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Navigation → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
  /**
   * Website Name field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The name of the website.
   * - **API ID Path**: navigation.default.primary.website_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_name: prismic.KeyTextField;

  /**
   * Menu Items field in *Navigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.menu_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_items: prismic.GroupField<
    Simplify<NavigationSliceDefaultPrimaryMenuItemsItem>
  >;
}

/**
 * Default variation for Navigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navigation*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * Navigation Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<
  "navigation",
  NavigationSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataMenuItemsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ReviewDocument,
      ReviewDocumentData,
      ReviewDocumentDataSlicesSlice,
      AllDocumentTypes,
      NavigationSlice,
      NavigationSliceDefaultPrimaryMenuItemsItem,
      NavigationSliceDefaultPrimary,
      NavigationSliceVariation,
      NavigationSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
